name: Build macOS Application

on:
  push:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Debug - Check what's installed
      run: |
        python -c "import numpy; print('NumPy:', numpy.__version__)"
        python -c "import matplotlib; print('Matplotlib:', matplotlib.__version__)"
        python -c "import sympy; print('SymPy:', sympy.__version__)"
        python -c "import tkinter; print('Tkinter available')"
        
    - name: Test script imports
      run: |
        cd src
        python -c "
        import matplotlib
        matplotlib.use('TkAgg')
        import volume_calculator_gui
        print('✅ All imports successful!')
        "
        
    - name: Build application with detailed output
      run: |
        python setup.py py2app 2>&1 | head -100
        echo "=== Build command finished ==="
        
    - name: Check build results
      run: |
        echo "=== Checking build folder ==="
        ls -la build/ || echo "No build folder"
        echo "=== Checking dist folder ==="
        ls -la dist/ || echo "No dist folder"
        echo "=== Checking for .app file ==="
        find . -name "*.app" -type d 2>/dev/null || echo "No .app files found"
        
    - name: Build with alias mode (debug)
      run: |
        python setup.py py2app -A
        echo "=== Alias mode build finished ==="
        ls -la dist/ || echo "No dist folder in alias mode"
        
    - name: Create ZIP if app exists
      id: zip_creator
      run: |
        if [ -d "dist/volume_calculator_gui.app" ]; then
          echo "✅ App found, creating ZIP"
          cd dist
          zip -r VolumeCalculator-macOS.zip volume_calculator_gui.app
          ls -la
          echo "ZIP_CREATED=true" >> $GITHUB_OUTPUT
        else
          echo "❌ No app found in dist folder"
          echo "ZIP_CREATED=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Upload artifact
      if: steps.zip_creator.outputs.ZIP_CREATED == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: VolumeCalculator-macOS
        path: dist/VolumeCalculator-macOS.zip
        retention-days: 30
