name: Build macOS Application

on:
  push:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        # Install system libraries needed for matplotlib
        brew install libpng freetype pkg-config
        
    - name: Install Python dependencies with pre-built wheels
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        # Install with --no-build-isolation to use system libraries
        pip install --no-build-isolation --only-binary=:all: -r requirements.txt
        
    - name: Verify installations
      run: |
        python -c "import numpy; print('NumPy:', numpy.__version__)"
        python -c "import matplotlib; print('Matplotlib:', matplotlib.__version__)"
        python -c "import sympy; print('SymPy:', sympy.__version__)"
        python -c "import tkinter; print('Tkinter available')"
        
    - name: Build application
      run: |
        python setup.py py2app
        
    - name: Check build results
      run: |
        echo "=== Checking for .app file ==="
        if [ -d "dist/volume_calculator_gui.app" ]; then
          echo "✅ App created successfully!"
          ls -la dist/volume_calculator_gui.app/Contents/
        else
          echo "❌ No app file found"
          echo "=== Checking dist folder ==="
          ls -la dist/ || echo "No dist folder"
          echo "=== Checking build folder ==="
          ls -la build/ || echo "No build folder"
        fi
        
    - name: Create ZIP if app exists
      if: success()
      run: |
        cd dist
        zip -r VolumeCalculator-macOS.zip volume_calculator_gui.app
        
    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: VolumeCalculator-macOS
        path: dist/VolumeCalculator-macOS.zip
        retention-days: 30
