name: Build macOS Application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [created]

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        brew update
        # Install any system dependencies if needed
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build application with py2app
      run: |
        python setup.py py2app
        # Check if the app was created
        ls -la dist/
        
    - name: Test the application (basic check)
      run: |
        # Check if the app structure is correct
        file dist/volume_calculator_gui.app/Contents/MacOS/volume_calculator_gui
        # Check the Info.plist
        plutil -p dist/volume_calculator_gui.app/Contents/Info.plist
        
    - name: Create ZIP archive
      run: |
        cd dist
        zip -r VolumeCalculator-macOS.zip volume_calculator_gui.app
        ls -la
        
    - name: Upload macOS application artifact
      uses: actions/upload-artifact@v4
      with:
        name: VolumeCalculator-macOS
        path: dist/VolumeCalculator-macOS.zip
        retention-days: 30
        
    - name: Upload to GitHub Release (if triggered by release)
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/VolumeCalculator-macOS.zip
        asset_name: VolumeCalculator-macOS.zip
        asset_content_type: application/zip
